export const products = [
    {
        id: "moonlight-pearl-necklace",
        slug: "moonlight-pearl-necklace",
        name: "Moonlight Pearl Necklace",
        price: 45000,
        category: "Necklaces",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
        description: "A cascade of iridescent freshwater pearls suspended from a delicate 18k gold chain. Each pearl is hand-selected for its unique luster and shape, creating a piece that is truly one-of-a-kind.",
        materials: "Freshwater Pearls, 18k Gold Plated Brass",
    },
    {
        id: "celestial-bracelet",
        slug: "celestial-gold-bracelet",
        name: "Celestial Gold Bracelet",
        price: 32000,
        category: "Bracelets",
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=1000&auto=format&fit=crop",
        description: "Intricately woven gold fibers create a light-catching lattice work that wraps comfortably around the wrist. Perfect for both daytime elegance and evening allure.",
        materials: "Sterling Silver Base, 24k Gold Vermeil",
    },
    {
        id: "floral-gajra-artisan",
        slug: "floral-artisan-gajra",
        name: "Floral Artisan Gajra",
        price: 18000,
        category: "Artisan Pieces",
        image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=1000&auto=format&fit=crop",
        description: "A modern homage to traditional craftsmanship. Hand-carved ivory-toned beads mimicking jasmine buds, designed to be worn as a statement of cultural heritage and refined taste.",
        materials: "Surgical Steel, Hand-finished Resin Beads",
    },
    {
        id: "emerald-teardrop-earrings",
        slug: "emerald-teardrop-earrings",
        name: "Emerald Teardrop Earrings",
        price: 28000,
        category: "Earrings",
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
        description: "Rare forest-green stones cut in a classic pear shape, set in a minimal claw setting to maximize light entry and reveal the stone's deep inner fire.",
        materials: "Lab-grown Emerald, 18k Gold Plate",
    },
    {
        id: "aura-silk-pendant",
        slug: "aura-silk-pendant",
        name: "Aura Silk Pendant",
        price: 22000,
        category: "Necklaces",
        image: "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?q=80&w=1000&auto=format&fit=crop",
        description: "A singular gold disc with a subtle hammered texture, evoking the soft glow of sunset on the ocean. A minimalist statement that speaks volumes.",
        materials: "14k Solid Gold",
    },
    {
        id: "velvet-rose-choker",
        slug: "velvet-rose-choker",
        name: "Velvet Rose Choker",
        price: 15500,
        category: "Artisan Pieces",
        image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop",
        description: "A statement piece featuring hand-stitched silk flowers on a premium velvet band. Elegance that demands attention and captures hearts.",
        materials: "Silk, Velvet, Gold-plated Clasp",
    }
];

